### ISSUE TITLE
SyncReader Esc issues

### ISSUE THREAD

**Issue by Anfid** [TimonPost/crossterm#114]
Hello. I have been playing with crossterm, testing it on various input data. Currently SyncReader does not recognize Esc key unless it is pressed twice.

If i get it correctly, this happens because SyncReader tries to poll next event to recognize escape sequence and  returns Esc key only when next() returns None. However, SyncReader does not return None and blocks instead.

**Comment by TimonPost** [comment]
Hello, thanks for telling, this is a known problem someone noticed me a few days ago too. I did not encounter it my self and I will have to investigate in what could cause this. 

Which platform are you on?

**Comment by TimonPost** [comment]
Fixed in #115
