### ISSUE TITLE
add support for terminal resize events

### ISSUE THREAD

**Issue by prabirshrestha** [TimonPost/crossterm#121]
Similar to `InputEvent` is there a `ResizeEvent` that I can listen to so that I can force redraw?

**Comment by TimonPost** [comment]
No there isn't, I think this would be a nice feature.

**Comment by TimonPost** [comment]
For windows we can use:
- https://docs.microsoft.com/en-us/windows/console/input-record-str#members
Caught here: https://github.com/TimonPost/crossterm/blob/master/crossterm_input/src/input/windows_input.rs#L176

For Unix there are a couple of options but it gets a bit tricky, it requires opening a thread:
- cursive: https://github.com/gyscos/Cursive/blob/master/src/backend/resize.rs
- termion discussion: https://gitlab.redox-os.org/redox-os/termion/issues/151

This solution seems to be the easiest to implement: 
- https://github.com/osa1/tiny/blob/master/term_input/src/lib.rs#L80 and
https://github.com/osa1/tiny/blob/master/term_input/src/lib.rs#L212

**Comment by TimonPost** [comment]
Closing in favor of https://github.com/TimonPost/crossterm/issues/165
