### ISSUE TITLE
OS X cursor position sometimes 0,0

### ISSUE THREAD

**Issue by sdgluck** [TimonPost/crossterm#122]
Hello,

Thanks for an awesome lib! I am developing some Node bindings for it to use it in a CLI I am building as there is no cross-platform lib in Node that allows reliably getting cursor position.

On to the problem:

On OS X 10.13.6 when I get the terminal cursor I always get back (0, 0).
Tried with iTerm2 and Terminal.
Pics: [1](https://i.imgur.com/tIilQ4w.png), [2](https://i.imgur.com/ZYQoIur.png)

On my Windows 10 machine I get the correct coords.
Tried with Git Bash.
Pics: [1](https://i.imgur.com/zuKbUSG.png)

My code: https://github.com/sdgluck/node-crossterm/blob/master/native/src/lib.rs#L23

I'm new to Rust so it may be a problem with my lib code, in which case sorry about that!

**Comment by TimonPost** [comment]
Can you do a debug on: `let (x, y) = cursor().pos();`. I am wondering if the problem could be caused by those lines: `let x_num = cx.number(x as f64);`. 

If you do a debug, we can better see where the problem is coming from.

**Comment by sdgluck** [comment]
Yep, can do this evening. Until then, did you see pic 2 (https://i.imgur.com/ZYQoIur.png)?

**Comment by keur** [comment]
I am having the same issue on OSX in iTerm2. Specifically, if I call `read_async` before getting the cursor position it happens. Removing the `read_async` function gives me the expected cursor position.

```rust
let input = input();
let mut stdin = input.read_async();
println!("something");
let (cx, cy) = cursor.pos();
```

**Comment by TimonPost** [comment]
Interesting, `(0,0)` is returned in cases of an error, some debugging with crossterm on macos needs to happen to see what the error is. I don't have a Mac PC at reach. If there are people able to help out here I'd appreciate it. Otherwise, it will take a bit longer to get this fixed.

**Comment by TimonPost** [comment]
I think that I just fixed this issue, I'll create a PR as soon as possible.

**Comment by keur** [comment]
Thank you!

**Comment by TimonPost** [comment]
can you try this branch and see if that solves the problem? https://github.com/TimonPost/crossterm/pull/134
