### ISSUE TITLE
Windows 10 / PowerShell Issues

### ISSUE THREAD

**Issue by MOZGIII** [TimonPost/crossterm#124]
I'm on Windows 10 and running my app in PowerShell console.

My app reacts to Enter key (char `13`), and it triggers the reaction immediately after the start. I tracked down the problem to the fact that it's processing the Enter key that I was using to invoke the command from the cli.

I.e.:

1. I type ` .\target\debug\myapp.exe`
2. I press "Enter" key.
3. My app starts and immediately triggers "Enter" key handler (cauisng it to quit in my case).

I expect step 3 to be "My app starts and waits for input".

I tried both sync and async input - the behaviour is the same.

**I'm using `fixes` branch.**

**Comment by TimonPost** [comment]
Yes, I'm usually developing on powershell too, and I know about this behavior. The enter you use to start the application is processed directly. I want to see if CMD had this behavior too. 

If CMD does not have this behavior its a powershell bug. Powershell has more of those problems, an other one was for example the dark yellow who wasn't implemented well.

**Comment by MOZGIII** [comment]
Good old cmd.exe works. I have another problem with it - in particular, I’m using `tui` (a branch that integrates `crossterm` 0.9) and the text doesn’t render as bold. This is not related, but is another blocker for me.
Also, in “git bash” on Windows my app doesn’t even start. Not sure why. I’ll probably create another issue for this one if I’m able to pin point that issue to crossterm.

**Comment by MOZGIII** [comment]
If this is a PowerShell bug - can there be a hack implemented in crossterm to work around it?
Or what can I do there? Maybe there’s a workaround I could implement at the app side?

**Comment by TimonPost** [comment]
You can work arround the problem, just ignoring the first enter hit.

Bold; your using powershell, as said before powershell does weird sometimes and CMD might work perfect, can you try that too?

Git bash; i thought that I had fixed this issue. I can check that out. You can create an issue for it.

**Comment by MOZGIII** [comment]
Bold; In powershell I wasn't able to see how it renders, so I can't tell if bold rendering works, since it closes immediately :) I encountered that issue with CMD. I switched to testing other platforms, but now I'm going back to look into it again in more detail. I should open a separate issue for that. The problem is I'm using tui and the unstable wip branch that integrated crossterm 0.9 - so I'm not sure where to address that issue. It may be that crossterm works perfectly and tui  Any hints?

Git bash; I'll open an issue after I test it without my app code involved, cause it may also crash with the similar error.

**Comment by TimonPost** [comment]
I am sorry to say but I messed up that branch, there will be a new PR soon.

**Comment by MOZGIII** [comment]
Oh, I see, got it. Thanks for letting me know!

**Comment by TimonPost** [comment]
Please check this one out: https://github.com/fdehau/tui-rs/pull/153

**Comment by MOZGIII** [comment]
Tried it, however the results are idential. Same issue with bold text not working, same issue with git-bash.

Furthermore, I've had very similar results with `termion`'s windows support PR as a `tui` backend.

So, with git-bash, the error I got look like this:

```shell
$ app.exe
Getting mode failed
Error: The handle is invalid. (os error 6)
```

Looks very similar to https://github.com/TimonPost/crossterm/issues/90

**Comment by MOZGIII** [comment]
For git-bash I created a separate tracking issue #125.

**Comment by lzybkr** [comment]
This is more of a .Net issue than a PowerShell issue.

The .Net api `Console.ReadKey` returns on key down, see [here](https://github.com/dotnet/corefx/blob/f37461280a3c843000aa79642ba700baa5a1fc30/src/System.Console/src/System/ConsolePal.Windows.cs#L195) and [here](https://github.com/dotnet/corefx/blob/f37461280a3c843000aa79642ba700baa5a1fc30/src/System.Console/src/System/ConsolePal.Windows.cs#L304).

This could maybe be addressed in PowerShell (or more specifically PSReadLine) by consuming the key up event before returning the completed command line. If you'd like to see that happen, I suggest opening an [issue](https://github.com/lzybkr/PSReadLine/issues/new) or even better, submit a PR.

**Comment by MOZGIII** [comment]
Hey @lzybkr, that's an pretty in-depth point of view on this problem, thanks!

I created an issue. Maybe it's not a good one, but it's at least a start. Feel free to add more details in the comments.
I don't have much experience with PowerShell/C# actually, so don't expect a PR from me any time soon. 😞 

I'm afraid that, even if it's fixed at `PSReadLine`, the fix won't arrive to the actual end users up until the next major Windows update, or maybe event the next one if the fix is not made in time.
@lzybkr what would be the release cycle for such kind of fix?

**Comment by lzybkr** [comment]
You're right about Windows releases - it can take a long time from when a fix is made before the fix is available in a Windows release. Also - I don't have any control over what fixes the PowerShell team picks up for Windows releases.

Note that PSReadLine is also released in PowerShell gallery as releases are ready, so affected users can easily pick up a release with a fix.  I haven't been very active in maintaining PSReadLine though, the PowerShell team might be taking over for me in that regard.

**Comment by MOZGIII** [comment]
Well, in that case I could potentially bundle the fixed version of PSReadLine with my software and make it easiliy installable for the end users if the choose to (i.e. via installer option).
This means fixing it in the PSReadLine is a practical thing to do. I'll see if I can help, but still - I have no experience with dotnet and related stuff. It might be quicker for me to build and just only ship the GUI version of the app - rather than going through the loop of solving the PowerShell issues.

**Comment by longwusha** [comment]
@TimonPost 

There are some problems with keyboard events in powershell, which will get the last keystroke event that you pressed before running. For example, when you run cargo run, you press the enter key (this time the button is obviously pressed before the program is compiled and run, and it has been processed by powershell), then when the program first tries to get the button When the event, it will get the enter event.

**Comment by longwusha** [comment]
![cmd](https://user-images.githubusercontent.com/22556004/57122618-c64b3500-6db0-11e9-9624-202055563d11.PNG)
![powershell](https://user-images.githubusercontent.com/22556004/57122621-c814f880-6db0-11e9-8f54-a16852dca470.PNG)

**Comment by TimonPost** [comment]
Did you read the above comments? It is a known issue in powershell.

**Comment by longwusha** [comment]
Sorry, I didn't look at the comments above carefully.

**Comment by TimonPost** [comment]
I think that this can be closed? Crossterm is and will not be capable of ignoring the Enter key only for powershell.
