### ISSUE TITLE
Release tags on github?

### ISSUE THREAD

**Issue by longwusha** [TimonPost/crossterm#126]
It seems that there is not any release tags on github. Any plan about creating release tags on github? I think it will be helpful for someone want to checkout a history release version.

**Comment by TimonPost** [comment]
Good question, I was questioning my self, too. I think that's possible.

**Comment by joseluis** [comment]
I also miss release tags, specially now that github allows to watch releases only.

**Comment by TimonPost** [comment]
I want to do this, but I am questioning if I should tag all 24 versions, this will take some time and history scrolling to set up.

**Comment by joseluis** [comment]
I think it's enough to tag the current version, and the new ones.

The past releases could be tagged eventually.

**Comment by felixrabe** [comment]
+1 so much!

I did some digging for you so you can (start to) follow the [Rust API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/) regarding this:


## Why + What

Crates which do not have corresponding release tags on Git(Hub) for versions published to crates.io make it hard to pin down the exact Git commit used to create the published version.

> If using Git to track the source of a crate, every release published to crates.io should have a corresponding tag identifying the commit that was published.

— https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-relnotes

This refers to every release listed on https://crates.io/crates/crossterm/versions.


## How

I suggest you take a recent version, like `crossterm 0.9.2`, and start consequently tagging releases from then on:

```sh
git tag -a -m "Release 0.9.2" "0.9.2" ":/0.9.2"
git tag -a -m "Release 0.9.3" "0.9.3" ":/0.9.3"
```

(I've executed the above commands locally, they should work for you too.) You should then be able to

```sh
git push origin --tags master
```

to get the tags pushed to GitHub.

Displaimer: I haven't actually released anything on GitHub. For more information, have a look at https://help.github.com/en/categories/releases (and RT(F)Ms e.g. Git manpages and stuff, of course) – just trying to help you get started here :)


## Simplify

I suggest you unify the version across all your `crossterm*` crates, which would result in something like https://github.com/serde-rs/serde/tree/v0.9.8 (note the "Release 0.9.8" message across all `serde*` crates).

If you don't want to unify: the `rand` crate also seems to use different versions for its subcrates as well, so you might have a look at https://github.com/rust-random/rand/releases for an example of doing it this way.


## The End

Keep going and happy coding! 🎉

**Comment by felixrabe** [comment]
For more examples of release pages, check the most downloaded crates on https://crates.io/: [libc](https://github.com/rust-lang/libc/releases), [rand](https://github.com/rust-random/rand/releases), [bitflags](https://github.com/bitflags/bitflags/releases).

**Comment by TimonPost** [comment]
Going to close this will be done from now on.
