### ISSUE TITLE
Attribute setting "normal intensity" is not exposed.

### ISSUE THREAD

**Issue by thomcc** [TimonPost/crossterm#136]
This is code 22. I believe this is often used instead of `NoBold` because it's present in more places. At a minimum, it's present on macOS, whereas `NoBold` is not.

As I mentioned in the other issue (#135), I don't exactly have access to non-mac machines, so I can't tell you what the status is there, but it seems that it's odd for this to be missing.

**Comment by TimonPost** [comment]
Should I call this attr `Attribute::NormalIntensity`?

**Comment by thomcc** [comment]
Up to you. That makes sense to me.

**Comment by TimonPost** [comment]
https://github.com/TimonPost/crossterm/pull/139
