### ISSUE TITLE
input().read_char() reads a whole line

### ISSUE THREAD

**Issue by getreu** [TimonPost/crossterm#137]
`input().read_char()` reads a whole line instead of only one character. I have observed this only under Linux. The Windows binary works as intended.

**Comment by TimonPost** [comment]
I saw encountered this one my self too, I will have a look at this!

**Comment by TimonPost** [comment]
I think that I will remove `read_char` from the API. This will be replaced with `read_sync()` or some easier call that returns a `KeyEvent`.

**Comment by TimonPost** [comment]
I'll close this because of the above
