### ISSUE TITLE
Input buffer to small Windows 7 

### ISSUE THREAD

**Issue by sigmaSd** [TimonPost/crossterm#141]
tested on windows 7 cmd and powershell msvc and gnu toolchain
```rust
let stdin = input.read_sync();
stdin.next()
```
In: thread 'main' panicked at '"Espace insuffisant pour traiter cette commande." })', src\libcore\result.rs:997:5ssage:
stack backtrace:
   0: std::sys_common::backtrace::_print
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\sys_common\backtrace.rs:70
   1: std::panicking::default_hook::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:200
   2: std::panicking::default_hook
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:215
   3: std::panicking::rust_panic_with_hook
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:478
   4: std::panicking::continue_panic_fmt
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:385
   5: std::panicking::rust_begin_panic
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:312
   6: core::panicking::panic_fmt
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libcore\panicking.rs:85
   7: core::result::unwrap_failed<crossterm_utils::error::ErrorKind>
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\macros.rs:17
   8: core::result::Result<(u32, alloc::vec::Vec<u8>), crossterm_utils::error::ErrorKind>::unwrap<(u32, al:ErrorKind>or:
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libcore\result.rs:798
   9: crossterm_input::input::windows_input::{{impl}}::next
             at C:\Users\packard bell\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_input-0.3.3\src\inpurs:1
  10: irust::term::Term::run
             at .\src\term.rs:67
  11: irust::main
             at .\src\main.rs:11
  12: std::rt::lang_start::{{closure}}<()>
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libstd\rt.rs:64
  13: std::panicking::try::do_call<closure,i32>
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\panicking.rs:297
  14: panic_unwind::__rust_maybe_catch_panic
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libpanic_unwind\lib.rs:87
  15: std::rt::lang_start_internal
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\/src\libstd\rt.rs:48
  16: std::rt::lang_start<()>
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997\src\libstd\rt.rs:64
  17: main
  18: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  19: BaseThreadInitThunk
  20: RtlUserThreadStart

**Comment by TimonPost** [comment]
I think I heard this error before, it had to do with that windows 7 had a much smaller input buffer then windows 7 and linux. I think I can make an update in crossterm for this.

**Comment by svartalf** [comment]
@TimonPost it was fixed (at least I thought it was) at #120

**Comment by svartalf** [comment]
So, since I've got the same issue again (after switching from the git dependencies to the crates-io one), I dug a little bit and the thing is — fix from the #120 into a `crossterm_winapi` crate was not published yet.

**Comment by TimonPost** [comment]
crossterm_winapi 0.1.3 is released, that one should not have this problem anymore.

**Comment by prabirshrestha** [comment]
This just reminded me of this two PRs in vim.
https://github.com/vim/vim/pull/3782
https://github.com/vim/vim/pull/3920

**Comment by TimonPost** [comment]
Fixed with 0.9.5 release
