### ISSUE TITLE
Make terminal.write() accept StyledObjects

### ISSUE THREAD

**Issue by sigmaSd** [TimonPost/crossterm#142]
So we can do terminal.write("hello".blue())
I dont know how difficult it is to implement, I just feel it would be a great improvement to the api, I know that in my current project at least it will make the code way better instead of having to use color::set_fg color::reset everywhere

**Comment by sigmaSd** [comment]
Actually now I dont feel that strongly about this anymore

**Comment by TimonPost** [comment]
O sorry, forgot to react, you can just use `write!` or `println!` and use the `Colored` type like: `println!("{}", Colored::Bg(Color::Red));`

**Comment by sigmaSd** [comment]
Ok thanks!
