### ISSUE TITLE
Clear Screen like cls on windows 8+ possible?

### ISSUE THREAD

**Issue by cyberpunkbln** [TimonPost/crossterm#146]
Hello,
only a short question on terminal().clear(ClearType::All). Is it possible to do a clear screen like cls command in cmd/powershell? At the moment the complete buffer is showable with scroll up.
thx

**Comment by TimonPost** [comment]
Sorry, I am not very sure what you mean with: "At the moment the complete buffer is showable with scroll up". If your app only runs on windows you might want to use `std::process::Command` with 'cls' as an argument.

**Comment by cyberpunkbln** [comment]
I mean that the ClearType::All is not an complete clear of the console, i can scroll up and see the output before start cargo run. The command cls complete flush the buffer.

I have tried the std::process::Command with cls but it don't functioned, with cmd/c and without.

When i try to make a curse-menu-like where i clean every submenu and so so the user can scroll up and see the submenus before.

I see that right, when i use
```
crossterm = "*"
extern crate crossterm;
use crossterm::{terminal,ClearType};
use crossterm::{Colored, Color, Colorize, Styler, Attribute};
use crossterm::cursor;
use crossterm::{input, InputEvent, KeyEvent, MouseButton, MouseEvent, RawScreen};
use std::{thread, time::Duration};
```

The i have the complete Crate/Library loaded that load features what for an os i have and i can only load features??? (crossterm_winapi) when i want only winapi console features, i think. The winapi crate/feature is not more c,omaptible are the same with the whole crate/lib?

`pub fn clear_entire_screen()` deletes only the buffer that i see in the console window. In the ansi terminal i see an ansi code.

Yes i know crosssystem clear console is a big black hole. Thousand workarounds;).

First give it an table with ansi codes for cmd and powershell and when different (there are different;)) give it an choice to detect which console i run and not only which OS i run?

Another thing in my brain ist that we can flush not the visible window (great idea) but flush the complete buffer, i mean scan the complete buffer then flush and set the cursor to position 0,0?

But for now ClearType::All is the best method, when i start complete the executable from explorer or fresh cmd/powershell.

**Comment by TimonPost** [comment]
Ah like that, crossterm will use WinApi for all windows versions below 10. So on windows 8 WinApi is used. 

It is possible that it does not behave like that, I am wondering if it does have that behavior on Linux. If Linux does clear the wole buffer windows should do that as well. I need to test that...

**Comment by cyberpunkbln** [comment]
Cool thx, i code under windows 10 at the moment. See i that right that Windows 10 are a problem case? Understand i that right, that clear the visible buffer is a hack under Windows 10 and with the WinApi all are right?

**Comment by cyberpunkbln** [comment]
@TimonPost Give it some news, why under windows 10 the fallback will be triggered? How i understand that problem is that under Win8 crossterm uses the ansi-codes.

**Comment by cyberpunkbln** [comment]
@TimonPost How i understand your code you send ansi-codes to unix like terminals and clear the viewable buffer in windows consoles? Give it no possibilty to clear the whole buffer in windows terminals with the winapi for powershell and cmd consoles?

**Comment by TimonPost** [comment]
>  See i that right that Windows 10 are a problem case? 
> Understand i that right, that clear the visible buffer is a hack under Windows 10 and with the WinApi all are right?
> Give it some news, why under windows 10 the fallback will be triggered? How i understand that problem is that under Win8 crossterm uses the ansi-codes.
> How i understand your code you send ansi-codes to unix like terminals and clear the viewable buffer in windows consoles?
> Give it no possibilty to clear the whole buffer in windows terminals with the winapi for powershell and cmd consoles?

Hello, I don't understand the questions you are trying to ask, they are very strange formulated. Can you make one better-formulated question from those?

**Comment by cyberpunkbln** [comment]
@TimonPost Sorry for the strange formulated questions, i try a new one:).

When i call the ClearType::All under Windows 10 and cmd/powershell it doesn't clear the complete buffer, it only deletes the viewable buffer. So that users can scroll up and see the previously typed buffer.

Command -> "cmd /c cls" do that right. Clears the complete buffer. I think the WinApi must clear the whole buffer, too why the cli-command cls uses the winapi to clear the screen/buffer complete on all windows terminals/consoles (cmd/powershell).

It seems that your Library don't choose the winapi, it chooses the fallback with visible Buffer hack, where only the visible viewport will be cleared.

**Comment by cyberpunkbln** [comment]
@TimonPost Okay short an precise. Can you replicate the clear screen from ansi terminals (full buffer) in windows terminals? A clear screen on windows like cls and not like clear all visible buffers. Has the WinApi no command to clear screen? You calcultate for windows width-key-height and width and clear this visible viewport, for ansi terminals you fire an ansi command that 100% replicate clear or cls?

**Comment by TimonPost** [comment]
I will take a look into this, I think I might have an idea how to implement this properly. Thanks for your issue and explanation.

**Comment by TimonPost** [comment]
Closed in favor of https://github.com/TimonPost/crossterm/issues/164
