### ISSUE TITLE
Reading From Screen?

### ISSUE THREAD

**Issue by rosenjcb** [TimonPost/crossterm#149]
I understand that you can clear the screen or line using `terminal.clear()` with the supplied enum value. However, is there any way to read what is currently on the screen?  I was looking into `input` but I believe this is for capturing live input. This may or may not be a dumb question. 

It looks like much of the functionality of crossterm (Unix and Windows 10 at least) is produced via ANSI escape codes. I.e. many of the features I see in crossterm are a 1-to-1 translation of a CSI code. https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_sequences

I personally don't have any idea how this works past my preliminary reading and source code review, so maybe reading is a lot more difficult than writing and clearing.

**Comment by TimonPost** [comment]
What do you want to read from the screen?

Like if it is the user input, you can capture it. The other things on the screen is something you put there your self with your application.
