### ISSUE TITLE
panicked: cannot get console mode

### ISSUE THREAD

**Issue by Rukenshia** [TimonPost/crossterm#15]
Hey,

one of my users is getting a weird error:

```thread 'main' panicked at 'Cannot get console mode', /cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.2.1/src/state/commands/win_commands.rs:48:21```

He's on Windows 7, tried using cmd, cygwin and cmder but always gets the same error.

**Comment by TimonPost** [comment]
I wil look at it in the evening thanks for reporting

**Comment by Rukenshia** [comment]
Currently on crossterm 0.2.1

**Comment by TimonPost** [comment]
If you upgrade to version 0.2.2 your error should be solved. Thanks for the reaction!
