### ISSUE TITLE
Incorrect terminal size on unix platforms

### ISSUE THREAD

**Issue by Canop** [TimonPost/crossterm#155]
`Terminal::new().terminal_size()` reports a height and width smaller by one compared to the number of characters you can count (and the one reported by ncurses or termion).

The error is here: https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/sys/unix.rs#L31

**Comment by TimonPost** [comment]
Closing this in favor of #162

**Comment by Canop** [comment]
I repeat there's zero relation with indexing. You can still have a 0 or 1 indexing and report the real number of characters fitting the width or height.

**Comment by TimonPost** [comment]
What do you purpose as a solution, I think that it makes stuff more complicated if we return both the index and the number of characters that fit in a with or height.

**Comment by Canop** [comment]
Indexing is a different problem. I'm just proposing to change the terminal_size function so that it returns the size of the terminal.

You just have to remove the -1 [here](https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/sys/unix.rs#L22).

**Comment by TimonPost** [comment]
Alright, so we can continue the description of this issue: #162 which is fixed in #170
