### ISSUE TITLE
Change terminal size results to be 1-based

### ISSUE THREAD

**Issue by TimonPost** [TimonPost/crossterm#162]
# Task Description
`Terminal::new().terminal_size()` reports a height and width smaller by one compared to the number of characters you can count (and the one reported by ncurses or termion).

The reason for this is that Windows is 0-based, and thus starts to count from 0 when it comes to terminal size, cursor position. Until now, cross-term maintained 0-based for everything. But it makes more sense to have it 1-based.

# Task Todo
- [ ] [Here ](https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/sys/unix.rs#L22)remove the '-1' from both `ws_col` and `ws_row`.
- [ ] [Here](https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/sys/winapi.rs#L12) add one to width and height, because windows starts counting at 0, and we need it to be 1.

**Comment by natbraun** [comment]
I can test this.

**Comment by natbraun** [comment]
From what I can see, we have to bring modifications to other places as well.

**Comment by TimonPost** [comment]
There is already a PR for this #170. The windows implementation does still need an update on this, however.

**Comment by natbraun** [comment]
> There is already a PR for this #170. The windows implementation does still need an update on this, however.
> 
> > From what I can see, we have to bring modifications to other places as well.
> > And those are?

https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/terminal/winapi_terminal.rs#L43

**Comment by TimonPost** [comment]
Yes, you're correct there, please check the second todo list box, which has a link to the place where the change needs to happen.

**Comment by natbraun** [comment]
Please have a look at this PR: https://github.com/TimonPost/crossterm/pull/176
