### ISSUE TITLE
Yank crossterm_style `0.3.4`

### ISSUE THREAD

**Issue by MSleepyPanda** [TimonPost/crossterm#184]
Releasing `crossterm_style` as `0.3.4` broke semver compatibility, as you introduced breaking changes re: trait bounds in #175.

**Crossterm `0.9.6` now fails in CI**

Please consider yanking `0.3.4` and republishing it as `0.4`.

**Comment by TimonPost** [comment]
Good idea forgot that I derived Clone for that type

**Comment by TimonPost** [comment]
It will be updated in a few minutes

**Comment by MSleepyPanda** [comment]
Thank you for your quick response!

**Comment by TimonPost** [comment]
crossterm_style is yanked and updated to be 0.4.0 as well as crossterm 0.10 and updated to 0.10.1
