### ISSUE TITLE
RIP copy paste of this file

### ISSUE THREAD

**Issue by jojolepro** [TimonPost/crossterm#20]
https://github.com/TimonPost/crossterm/blob/master/examples/Crossterm%200.3.0/crossterm_type/mod.rs

You can see the git diff "-" symbol at the start of each line

**Comment by TimonPost** [comment]
Oke, aww stupid I knew that will update it soon thanks thanks for noticing!.

**Comment by jojolepro** [comment]
Is there somewhere I can write to you except github? (discord, gitter)
I'd like to do something like the minecraft server command line, where the bottom line is reserved for input and the rest is for stdout regular output, and it needs to be crossplatform. From what I understood, you don't have keyboard input yet?

**Comment by TimonPost** [comment]
My Discrord: "Daposto"#4256

**Comment by jojolepro** [comment]
resolved
