### ISSUE TITLE
Terminal::terminal_size() vs size()

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#200]
It doesn't follow Rust naming guidelines. We have:

* `Terminal::set_size`
* `Terminal::terminal_size`

We should have:

* `Terminal::set_terminal_size`
* `Terminal::terminal_size`

Or:

* `Terminal::set_size`
* `Terminal::size`

It's a breaking change which should be handled via [An attribute for deprecation](https://doc.rust-lang.org/edition-guide/rust-2018/the-compiler/an-attribute-for-deprecation.html).

**Comment by TimonPost** [comment]
You are correct, for the naming sake, we can change that. I can as well just upgrade crossterm to 0.11. Deprecated stuff is annoying.

**Comment by TimonPost** [comment]
I would personly go for:

Terminal::set_size
Terminal::size

Because 'terminal' is repetitive since that is clear from the sruct you are using.

**Comment by zrzka** [comment]
Shorter is better and you're right that the deprecated attribute is annoying (at least till 1.0 will be reached).

**Comment by TimonPost** [comment]
# Taks
Rename [terminalsize](https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/terminal/terminal.rs#L107) to :

```rust
Terminal::size()
```
