### ISSUE TITLE
Terminal::set_size & terminal_size i16 vs u16

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#201]
Is there a reason that I can get the size as `u16` and set the size as `i16`? Shouldn't we use same type for getter / setter?

**Comment by TimonPost** [comment]
I would like to have it all to u16.

windows:
getsize returns i16
setsize requires i16

windows ANSI + UNIX:
getsize [returns ](https://github.com/TimonPost/crossterm/blob/master/crossterm_cursor/src/sys/unix.rs#L82)i16
setsize requires ([doesn't matter](https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/terminal/ansi_terminal.rs#L78))
