### ISSUE TITLE
Terminal::write -> Result<usize>

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#202]
What's the purpose of the `usize` in the result? `std::io::stdout::flush` returns `Result<()>` and the `Terminal::write` always returns `Ok(0)` (in case there's no error). Am I overlooking something?

**Comment by TimonPost** [comment]
write should return the number of bytes being written to the terminal. Flush does not return the size of bytes flushed to the stdout. This works similarly to [write ](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write) and [flush ](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.flush).

You are correct that it returns always 0, this must-have happened during the latest releases. 

https://github.com/TimonPost/crossterm/blob/master/crossterm_terminal/src/terminal/terminal.rs#L134

This
```rust 
        write_cout!(format!("{}", value))?;
        Ok(0)
```

Should be:

```rust 
let size = write_cout!(format!("{}", value))?;
Ok(size)
```

write_cout! does return the written size. But it is completely ignored in that function.
