### ISSUE TITLE
Travis - Not all tests are executed

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#205]
`.travis.yml` does contain following lines:

```bash
cargo fmt -- --check
cargo test -- --nocapture --test-threads 1
```

But these commands check formatting / test the `crossterm` crate only. An example - modify `crossterm_terminal/examples/terminal.rs` (make it not compilable) and then run `cargo test -- --nocapture --test-threads 1`. It passes. Same applies to formatting, etc.

**Comment by zrzka** [comment]
```bash
warning: output filename collision.
The example target `terminal` in package `crossterm_terminal v0.2.5 (/Users/robertvojta/Projects/personal/crossterm/crossterm_terminal)` has the same output filename as the example target `terminal` in package `crossterm v0.10.1 (/Users/robertvojta/Projects/personal/crossterm)`.
Colliding filename is: /Users/robertvojta/Projects/personal/crossterm/target/debug/examples/terminal.dSYM
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
```

**Comment by zrzka** [comment]
I saw that you did add GH Actions support, but here's my Travis CI change proposal anyway:

* Replace `rustup component add rustfmt-preview` with `rustup component add rustfmt`
* If `$TRAVIS_OS_NAME == "windows"` (just add `--all` to both)
  * `cargo fmt --all -- --check`
  * `cargo test --all -- --nocapture --test-threads 1`
* If `$TRAVIS_OS_NAME != "windows"` (add `--all` & `--exclude ...`)
  * `cargo fmt --all --exclude crossterm_winapi -- --check`
  * `cargo test --all --exclude crossterm_winapi -- --nocapture --test-threads 1`
* plus examples collisions (see above)
* plus remove `.travis.yml` files from nested folders

**Comment by TimonPost** [comment]
I will take that and move it into GH actions. Travis is probably going to be disabled.

**Comment by TimonPost** [comment]
https://github.com/TimonPost/crossterm/pull/215
