### ISSUE TITLE
Find a way how to avoid --exclude crossterm_winapi

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#220]
One has to run tests in the following way:

* Windows `cargo test --all -- --nocapture --test-threads 1`
* macOS/Linux - `cargo test --all --exclude crossterm_winapi -- --nocapture --test-threads 1`

Research if there's a way how to use `--all` without `--exclude` on all platforms.

Mr. Obvious here is to annotate everything (at least top level modules) with `#[cfg(windows)]`, which will lead to an empty crate on `!= Windows` platforms. Kind of dislike this, but if there won't be another way ...

**Comment by TimonPost** [comment]
But how is `crossterm_winapi` included for MacOs and Linux, the dependency is only added if the current operating system is windows right?

**Comment by zrzka** [comment]
It's caused by the `cargo test --all` & `workspace`. It basically tries to test `crossterm_winapi` subcrate as well and it fails. There's no way how to say _I'm Windows only crate_ in the `crossterm_winapi/Cargo.toml` file.

To make it work with `cargo test --all`, following is required:

* `Cargo.toml`: `[dependencies]` -> `[target.'cfg(windows)'.dependencies]`
* `src/lib.rs`: Annotate all `mod` & `pub use` with `#[cfg(windows)]`

**Comment by zrzka** [comment]
You can imagine `cargo test --all` as a:

```bash
for crate in Cargo.toml.workspace.members
do
  pushd $crate
  cargo test
  popd
done
```

**Comment by zrzka** [comment]
Here're the outputs on macOS:

* `cargo test` - [cargo-test.txt](https://github.com/TimonPost/crossterm/files/3615778/cargo-test.txt)
* `cargo test --all` - [cargo-test-all.txt](https://github.com/TimonPost/crossterm/files/3615777/cargo-test-all.txt) (errors)
* `cargo test --all --exclude crossterm_winapi` - [cargo-test-all-exclude.txt](https://github.com/TimonPost/crossterm/files/3615776/cargo-test-all-exclude.txt)

There's a huge difference between `--all` & without `--all` in the number of executed tests. Without `--all`, only `crossterm` crate tests are executed (subcrates tests are not executed).
