### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#221]
Currently there're top level examples (`crossterm`) and examples in subcrates (`crossterm_cursor/example`). This is causing _issues_ like:

* I can't run subcrate examples with `cargo run --example cc_cursor`
* Lot of duplicated code
* Build warnings (examples with the same name)
  * Will be hard error in the future
  * I prefixed them in the #222 as a temporary workaround

My proposal is to:

* Remove all subcrate examples
* Improve top level examples (merge them with the subcrate ones)

This is based on the fact that most people will use `crossterm` crate only (with features) directly.

**Comment by zrzka** [comment]
Reply from #222:

> I'm really doubting that we might want to remove the examples from the sub crates and instead use those in /examples, because all those examples are mostly duplicated with the only difference being the namespaces.

IMHO this can be solved by splitting imports in the root level example and adding a comment that `crossterm` should be replaced with `crossterm_...` if a subcrate is used directly. What bothers me:

* code duplication
* you can't run subcrate examples with simple `cargo run --example`
* it's not clear that these examples differ in the namespace only and when I saw them for the first time (directory structure, not the code itself) I thought that they're different

I'll show you what I mean with this issue & comment in a separate branch. I can delete it if you wont like it, no problem.

**Comment by TimonPost** [comment]
Exactly I prefer that as well because code duplication is a real pain. Just comment in the /examples/README.md, or in the example file would be good enough to tell the user that namespaces might vary on the crate they are using.

**Comment by TimonPost** [comment]
I am going to open a PR that removes all duplicated examples in subcrates

**Comment by zrzka** [comment]
Fixed by #225
