### ISSUE TITLE
WinApiCursor::pos call unwrap internally

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#223]
Compare `WinApiCursor::pos` and `AnsiCursor::pos`.

* `WinApiCursor` does call `unwrap` -> possible panic
* `AnsiCursor` returns `(0, 0)` in case of error -> no panic

Shouldn't the behaviour be synced? Return `(0, 0)` in case of error in the `WinApiCursor::pos`?

`WinApiCursor::pos`:

```rust
fn pos(&self) -> (u16, u16) {
    let cursor = Cursor::new().unwrap();
    cursor.position().unwrap().into()
}
```

`AnsiCursor::pos`:

```rust
fn pos(&self) -> (u16, u16) {
    get_cursor_position()
}

pub fn get_cursor_position() -> (u16, u16) {
    if unsafe { RAW_MODE_ENABLED } {
        if let Ok(pos) = pos_raw() {
            pos
        } else {
            (0, 0)
        }
    } else {
        if let Ok(pos) = pos() {
            pos
        } else {
            (0, 0)
        }
    }
}
```

**Comment by TimonPost** [comment]
Good idea

**Comment by imdaveho** [comment]
Quick follow up on this. I understand the benefits of keeping the behavior in sync -- definitely the way to go. However, is it appropriate to silently fail and return `(0, 0)` if there is an error fetching cursor position? Wouldn't that create unexpected behavior for the implementor and be best left up to them to handle?

**Comment by zrzka** [comment]
@imdahe I fully agree and I take this as a temporary _fix_.  Ideally, the result should be `Result(x, y)>`.  I have a list of API inconsistencies / problematic areas, have this problem on it and will create an issue soon.
