### ISSUE TITLE
Snake example on macOS

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#230]
* Barely readable input (size) with some colour schemes (Solarized Dark in my case)
* Incomplete border
* Weird looking snake after I make a turn (part of it is missing)
* Tail is not disappearing / moving

Is this a problem on other platforms like Linux / Windows as well?

<img width="1217" alt="Screenshot_2019-09-17_at_13_25_48" src="https://user-images.githubusercontent.com/1084172/65038260-df174a00-d94f-11e9-90d2-c6466f7a5c2f.png">

<img width="1217" alt="Screenshot_2019-09-17_at_13_25_28" src="https://user-images.githubusercontent.com/1084172/65038276-e8081b80-d94f-11e9-8fa7-ab5500f1a55d.png">

**Comment by TimonPost** [comment]
> Barely readable input (size) with some color schemes (Solarized Dark in my case)
Probably has to do with your color interpretation. Currently, it is green font on yellow background. It doesn't really look like that. This can be caused by either the terminal you are using or crossterm (powershell has a few problems with interpretation as well)
> Snake game is not 100% hufter proof. Snake game is made to quicly test: coloring, styling, input terminal clearing, cursor movent) I did not realy intend or had the time to make it 100% hufter proof. Some dimensions might not work very well and as you can see the character should probably be different for a sake moving horizontal and diagonal.

**Comment by zrzka** [comment]
Fixing it to make a proper game from it.

**Comment by zrzka** [comment]
Just a note to myself ... Welcome screen in the standard 80x24 terminal ...

<img width="842" alt="Screenshot 2019-09-17 at 21 24 02" src="https://user-images.githubusercontent.com/1084172/65072618-8b2d5500-d991-11e9-9f24-11689d79fe44.png">

**Comment by zrzka** [comment]
Sneak peek ...

<img width="1202" alt="Screenshot 2019-09-17 at 21 26 46" src="https://user-images.githubusercontent.com/1084172/65072938-23c3d500-d992-11e9-8be5-3b6c51348576.png">

<img width="376" alt="Screenshot 2019-09-17 at 21 28 05" src="https://user-images.githubusercontent.com/1084172/65072952-2b837980-d992-11e9-9402-a35408cd80aa.png">

... will finish it tomorrow with some new features :)
