### ISSUE TITLE
Review & test Upcoming docs.rs changes

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#233]
More info at: https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html

We have to be sure that we are in limits and docs will be available.

**Comment by TimonPost** [comment]
Good to know, I don't think we are going to have problems with those limits.

**Comment by zrzka** [comment]
`crossterm`:

```bash
$ time cargo doc --no-deps
real	0m4.361s
user	0m4.370s
sys	0m0.470s
```

`crossterm_cursor`:

```bash
$ time cargo doc --no-deps
real	0m1.378s
user	0m1.290s
sys	0m0.080s
```

`crossterm_input`:

```bash
$ time cargo doc --no-deps
real	0m1.400s
user	0m1.300s
sys	0m0.090s
```

`crossterm_screen`:

```bash
$ time cargo doc --no-deps
real	0m1.302s
user	0m1.210s
sys	0m0.080s
```

`crossterm_style`:

```bash
$ time cargo doc --no-deps
real	0m1.493s
user	0m1.350s
sys	0m0.120s
```

`crossterm_terminal`:

```bash
$ time cargo doc --no-deps
real	0m1.358s
user	0m1.230s
sys	0m0.120s
```

`crossterm_utils`:

```bash
$ time cargo doc --no-deps
real	0m1.383s
user	0m1.280s
sys	0m0.090s
```

`crossterm_winapi`:

* Fails to build

Except the `crossterm_winapi` which is failing to build, we're safe. No other dependencies are required. `crossterm_winapi` doc build issue is connected to #220.
