### ISSUE TITLE
TerminalCursor::pos/show/hide methods do not use ANSI codes on Windows

### ISSUE THREAD

**Issue by zrzka** [TimonPost/crossterm#246]
On Windows, if ANSI is supported, `TerminalCursor` does use `AnsiCursor` internally. But, there're three functions that still do use `ScreenBuffer`:

* `pos()`
* `show()`
* `hide()`

They do use `sys::get_cursor_position` & `sys::show_cursor`. In case of Windows, the ANSI version of them is not bundled because of `#[cfg(unix)]` & `#[cfg(windows)]`:

```rust
#[cfg(unix)]
pub(crate) use self::unix::get_cursor_position;
#[cfg(unix)]
pub(crate) use self::unix::show_cursor;
#[cfg(windows)]
pub(crate) use self::windows::get_cursor_position;
#[cfg(windows)]
pub(crate) use self::windows::show_cursor;

#[cfg(unix)]
pub(crate) mod unix;

#[cfg(windows)]
pub(crate) mod windows;
```

Is this a bug or is it intentional (like Windows doesn't support those specific escape sequences)?

**Comment by zrzka** [comment]
I'd expect something like this (with `unix.rs` -> `ansi.rs`):

```rust
#[cfg(windows)]
use crate::Result;
#[cfg(windows)]
use crossterm_utils::supports_ansi;

mod ansi;

#[cfg(windows)]
pub(crate) mod windows;

#[cfg(windows)]
pub(crate) fn get_cursor_position() -> Result<(u16, u16)> {
    if supports_ansi() {
        ansi::get_cursor_position()
    } else {
        windows::get_cursor_position()
    }
}

#[cfg(unix)]
pub(crate) use ansi::get_cursor_position;

#[cfg(windows)]
pub(crate) fn show_cursor(show_cursor: bool) -> Result<()> {
    if supports_ansi() {
        ansi::show_cursor(show_cursor)
    } else {
        windows::show_cursor(show_cursor)
    }
}

#[cfg(unix)]
pub(crate) use ansi::show_cursor;
```

**Comment by zrzka** [comment]
Hmm, I probably found a reason for this. `unix` one utilizes `crossterm_utils::sys::unix`, etc.

**Comment by TimonPost** [comment]
It is intentional. Some actions are platform-specific or not supported by ANSI, we want to run the windows implementation when on windows, and the unix implementation on unix. That's why they call into `sys` who export that function.

**Comment by zrzka** [comment]
Surprising that I can set cursor position via ANSI sequence, but can't get cursor position via ANSI sequence.

**Comment by zrzka** [comment]
Anyway, thanks for the explanation. I'll add some comments about this.

**Comment by TimonPost** [comment]
ANSI escape codes are byte sequences that can be used to 'set' something. When you want to get something you have to write the command to the screen and read the bytes from the tty. This happens in the cases of user input and getting cursor position this is related to the problem we are having here (#199).

**Comment by zrzka** [comment]
Yep, I know, used wrong wording. Closing this one as there's nothing to do here.
