### ISSUE TITLE
Any interest in supporting input, not only output?

### ISSUE THREAD

**Issue by steveklabnik** [TimonPost/crossterm#26]
I realize this is a big ask :)

I was playing with crossterm today, and I really like it. But I need to deal with input, not only output. Do you have any intention of adding input someday? This isn't for anything important, but I'm curious...

**Comment by TimonPost** [comment]
Check the development branch :). I have been working on that the last month with some other refactorings.

**Comment by steveklabnik** [comment]
Ah that's awesome! I will give it a try and report back :)

**Comment by steveklabnik** [comment]
It's working pretty well! I'll share with you what I'm doing when (and if) it's ready. Thanks a ton, you rock!
