### ISSUE TITLE
raw pty

### ISSUE THREAD

**Issue by aep** [TimonPost/crossterm#30]
i'm implementing a remote shell thing. to connect it to a remote pty there's a bunch of tcsetattr flags missing. cfmakeraw is not enough

https://github.com/openssh/openssh-portable/blob/90e51d672711c19a36573be1785caf35019ae7a8/sshtty.c#L69

is this something that could be implemented? i rather like the way crossterm resets to original state and would like to use it

**Comment by TimonPost** [comment]
Yea sure, I'm not very confident with c API calls what they do an how they work. So if you say this is better I'll definitely will implement it like opensll and test if all things are still working so would be possible!

**Comment by aep** [comment]
well it breaks behavior for other people maybe, so maybe we'll need separate settings for that.

i'll play around and open a PR once i know the exact flags.

**Comment by TimonPost** [comment]
Cool, I am interested! This version is not out that long though so not much people will be affected I quess?

**Comment by TimonPost** [comment]
@aep did you had any time to look into this?

**Comment by aep** [comment]
unfortunately not. i didnt have time to dig into this, and i'm currently using raw nix instead. sorry!

**Comment by aep** [comment]
for what its worth: i dont understand why your code is not working for me. I think its correct and the problem must be somewhere else. closing this.
