### ISSUE TITLE
Implementing terminal::pause() functinality

### ISSUE THREAD

**Issue by GarkGarcia** [TimonPost/crossterm#39]
So apparently doing the equivalent of C's `System('pause')` in Rust is a bit harder than it should be, as you can see in [this discussion](https://users.rust-lang.org/t/rusts-equivalent-of-cs-system-pause/4494).

I just thought that since the focus of this crate is cross-platform terminal functionality and this is such a common thing to do (_Press any key to continue..._), maybe it could get implemented as a simple function like `terminal::pause()` or something along this lines.

If you think `pause()` is a bit too specific, `terminal::read_char()` or `stdin().read_char()` would be nice too.

**Comment by TimonPost** [comment]
Yea, seems a nice function to have. I'll investigate further into it.

**Comment by TimonPost** [comment]
I will make the follwing enum:

```
pub enum CloseType {
    OnKeyPress(u8),
    OnEnter,
    OnAnyKeyPress
}
```

the user will be able to call:

```
let terminal = terminal();
terminal.pauze(CloseType::OnEnter);
```

If you have better names our ideas I like to hear it. I'll be releasing it this or next week.

**Comment by TimonPost** [comment]
#47

**Comment by GarkGarcia** [comment]
Seems fine to me!

**Comment by czy-29** [comment]
How to achieve this capability for now? Four years have passed, and the terminal::pause function seems to have disappeared...

**Comment by TimonPost** [comment]
For input, reading refer to `poll` and `read` functions in the docs. Also checkout the `EventStream`. You should be able to use this API to achieve waiting for input.

**Comment by c-vision** [comment]
use crossterm::event::{read, Event};

pub fn pause() {
    loop {
        match read().unwrap() {
            Event::Key(_event) => break,
            _ => continue,
        }
    }
}
