### ISSUE TITLE
Flush buffer does not clear internal buffer.

### ISSUE THREAD

**Issue by imdaveho** [TimonPost/crossterm#41]
```
    terminal(&screen).clear(ClearType::All);
    cursor(&screen).goto(0, 0);
    screen.write_buf(b"https://www.google.com").expect("");
    screen.flush_buf().expect("");
    cursor(&screen).goto(4, 0);
    screen.write_buf(b"FFF").expect("");
    screen.flush_buf().expect("");
```

expecting the result to be:
> `httpFFF/www.google.com`

actual:
> `httphttps://www.google.comFFF`

seems like code isn't synchronous here...

**Comment by TimonPost** [comment]
Thanks for leaving the issue. I think I know what is going wrong here. 

If you check out the[ flush functioning](https://github.com/TimonPost/crossterm/blob/master/src/common/screen/screen.rs#L110) you can see that the inner buffer `Screen` does not clear (makes empty) the buffer. I can fix this fast, but does this have priority for you?

**Comment by imdaveho** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  take your time, no rush; just wanted to confirm that it was indeed a bug. I could look into it as well and maybe make a pr.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: November 14, 2018 2:40 AMTo: crossterm@noreply.github.comReply-to: reply@reply.github.comCc: imdaveho@gmail.com; author@noreply.github.comSubject: Re: [TimonPost/crossterm] cursor.goto and screen.write_buf conflict when rendering to screen? (#41)  Thanks for leaving the issue. I think I know what is going wrong here.
If you check out the flush functioning you can see that the inner buffer Screen does not clear (makes empty) the buffer. I can fix this fast, but does this have priority for you?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by TimonPost** [comment]
See #42.

**Comment by TimonPost** [comment]
I've released a new version please check out version: 0.4.3
