### ISSUE TITLE
Problems with input()::read_line() on version 5.1

### ISSUE THREAD

**Issue by GarkGarcia** [TimonPost/crossterm#55]
I've been experiencing a a few bugs related to character deletion on `input::read_line()`.

I believe this issues to be deeply related to the fact that I'm using a _portuguese-configured_ keyboard, which may map keys in a slightly different fashion. Also, I haven't tested this in any other platform besides **Windows 10**.

There are three main problems:

# First
When I press the `backspace` key the cursor will move to the left accordingly, but the last character of the displayed text will not be remove. If I then type another key, this new character will take it's place.

Also if I press the `backspace` key and then press `enter`, `read_line()` will return the text as if I hadn't pressed `backspace` in the first place.

# Second
If I keep pressing `backspace` until I get to the start of the line, _crossterm_ will keep moving the cursor back over previously printed text.

# Third
If I press any of the arrow keys, instead of moving the cursor, _crossterm_ will count that as an `à` character.

**Comment by GarkGarcia** [comment]
If you are not able to replicate this issues (it may be localized thing) let me know and I'll send you some screen recordings.

**Comment by TimonPost** [comment]
I'll be one it...

**Comment by TimonPost** [comment]
@GarkGarcia Did you enable with crossterm raw modes for your terminal? And could you provide some code that reproduces this?

**Comment by GarkGarcia** [comment]
Sure, here's my code:
```rs
extern crate crossterm;

use crossterm::{terminal::{terminal, Terminal, ClearType}, input};

fn main() {
    let prompt = terminal();
    read_input(&prompt, ans);
}

fn read_input(prompt: &Terminal) {
    match input().read_line() {
        Ok(input) => { */ Do some stuff /* },
        Err(_) => prompt.write("Bad stuff")
    }
    read_input(&prompt, ans);
}
```

I didn't enabled raw modes, in fact I don't even know what they are... Am I messing something up?

**Comment by TimonPost** [comment]
I have the same problem though, so it is not a problem you only have. One thing to note is that when using git bash on windows the output was correct. However, when using cmd I had the same problems.

**Comment by GarkGarcia** [comment]
Is this fixed then, or will the fixes come out in version `5.2`?

**Comment by TimonPost** [comment]
Sorry, it took this long to fix this issue, I had some other crates to maintain. I will release a new version as soon as possible and put my priority on it. Version 0.6 will be the next one. I also have some other changes for the new feature so 5 or 6 days should everything be finished.

Does this issue have priority for you? You might want to fork the master branch and use that as a dependency since it has the fixes of this issue.

**Comment by GarkGarcia** [comment]
Yeah sounds fine.
