### ISSUE TITLE
Basic attribute support for Windows systems.

### ISSUE THREAD

**Issue by Jezza** [TimonPost/crossterm#60]
AFAIK, the windows terminal does support attributes, such as bold, but it doesn't support a lot of *nix ones.

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

Is it a good idea to see if we can implement partial attributes?

**Comment by TimonPost** [comment]
You are right windows terminals are not supporting those. Not sure what you are meaning with 'partial attributes'. The link you sent is about the ANSI escape codes which could be used for Windows 10 systems. Currently, Windows 10 systems are already using ANSI escape codes instead of WinApi. 

Could you elaborate more on what you mean with 'partial support' or 'partial attributes'?

**Comment by Jezza** [comment]
As in, unless I'm understanding this incorrectly, that does show that it supports bold.:
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting

Bold is a valid value.

**Comment by TimonPost** [comment]
Ah, yea now I see. I did never saw those options in the document, must have overlooked them. This is actually really cool and will be implemented of course. Thanks for creating this issue and letting me know. 

Just for issue record:

The following attributes are needed to be implemented. 

Value | Description | Behavior
-- | -- | --
0 | Default | Returns all attributes to the default state prior to modification
1 | Bold/Bright | Applies brightness/intensity flag to foreground color
4 | Underline | Adds underline
24 | No underline | Removes underline
7 | Negative | Swaps foreground and background colors
27 | Positive (No negative) | Returns foreground/background to normal

Currently, this is already working for UNIX terminal and so it is just a mather of removing some `#[cfg(unix)]` attributes from the following methods. 

https://github.com/TimonPost/crossterm/blob/master/src/modules/style/styledobject.rs#L84
https://github.com/TimonPost/crossterm/blob/master/src/modules/style/styledobject.rs#L101
https://github.com/TimonPost/crossterm/blob/master/src/modules/style/styledobject.rs#L120

**Comment by Jezza** [comment]
Hm, I might be wrong.
While it says it supports it, the terminal would disagree...

![2o0ujj8](https://user-images.githubusercontent.com/4224088/50059271-0bb1f180-0185-11e9-839e-ddafe7130b92.png)

**Comment by Jezza** [comment]
Ok, nevermind.
I missed the foreach loops when I was removing the `cfg(unix)`s.
It works now, but my god, it's barely visible...
It's basically just more... white....

![j4ibywe](https://user-images.githubusercontent.com/4224088/50059414-bbd42a00-0186-11e9-8018-3220cf3ec0ba.png)

**Comment by TimonPost** [comment]
Awesome, work!
