### ISSUE TITLE
Panics after upgrading from 0.5.1 to 0.5.3

### ISSUE THREAD

**Issue by VladimirMarkelov** [TimonPost/crossterm#72]
Thank you for the great library. I like it :+1:

I am not sure if close issue 40 fixes the trouble but version 0.6 is not published yet.

OS: Window 7 Home 64 bit
Rust: 1.30 GNU-MinGW
Crossterm: 0.5.3

I started using your library a few weeks ago. It was 0.5.1. It worked smoothly. Today I ran cargo update and my application started panicking at line `let term = crossterm::terminal::terminal();`.

It shows:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 87, kind: Other, message: "The parameter is incorrect." }', libcore\result.rs:1009:5

I rolled back to 0.5.1. Should I wait for 0.6? Or it is a new bug and it needs some investigation?

**Comment by TimonPost** [comment]
It is probably a bug, please go back to 0.5.1 Are you sure you are using 0.5.3? I had this bug solved there since it occurred in 0.5.2. 0.5.2 has been yanked.

**Comment by TimonPost** [comment]
On what system are you?

**Comment by TimonPost** [comment]
For your case Windows 7 I suggest to go back a version, I've gotta install a Virtual machine first if I want to debug that.

**Comment by VladimirMarkelov** [comment]
I saw  `0.5.3` in Cargo.lock.  As I mention in the original post, I use Windows 7 that is not in the list of OSes that must work.

> Is let term = crossterm::terminal::terminal(); the only code you ran?

No, it is the first call to crossterm and them it exits with panic. Next call is request for terminal size.

**Comment by TimonPost** [comment]
Cool! I tested some time ago on Windows 7 too. So should suppose to work. I will do some research now. To which screen dimensions are you setting your terminal screen? Not that Windows 7 and 8 are having limits to the size.

**Comment by VladimirMarkelov** [comment]
```
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at libstd\sys\windows\backtrace/mod.rs:104
             at libstd\sys\windows\backtrace/mod.rs:95
   1: std::sys_common::backtrace::print
             at libstd\sys_common/backtrace.rs:71
             at libstd\sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: crossterm::kernel::windows_kernel::ansi_support::try_enable_ansi_support::{{closure}}
             at C:\Users\vvm\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.5.3\src\kernel\windows_kernel/ansi_support.rs:17
  11: std::sync::once::Once::call_once::{{closure}}
             at libstd\sync/once.rs:230
  12: std::sync::once::Once::call_inner
             at libstd\sync/once.rs:397
  13: std::sync::once::Once::call_once
             at libstd\sync/once.rs:230
  14: crossterm::kernel::windows_kernel::ansi_support::try_enable_ansi_support
             at C:\Users\vvm\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.5.3\src\kernel\windows_kernel/ansi_support.rs:15 
  15: crossterm::common::functions::get_module                                                                                            
             at C:\Users\vvm\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.5.3\src\common/functions.rs:71                   
  16: crossterm::modules::terminal::terminal::Terminal::new                                                                               
             at C:\Users\vvm\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.5.3\src\modules\terminal/terminal.rs:32          
  17: crossterm::modules::terminal::terminal::terminal                                                                                    
             at C:\Users\vvm\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm-0.5.3\src\modules\terminal/terminal.rs:177         
  18: colortest::main                                                                                                                     
             at src/main.rs:9                                                                                                             
```

**Comment by VladimirMarkelov** [comment]
it is output for simple application:

```rust
use crossterm;
fn main() {
    let term = crossterm::terminal::terminal();
    println!("{:?}", term.terminal_size());
}
```

**Comment by TimonPost** [comment]
I think I know why this is happening. It has to do with the error handling update I did. Currently for terminal_size() I kept the unwrap(). For now, I recommend staying at 0.5.1 for windows 7 or 8. I'll be updating a patch soon.

**Comment by TimonPost** [comment]
Could you try using `bug_fix` branch as a dependency to your program and see if it is working?

```
[dependencies]
crossterm= { git = "https://github.com/TimonPost/crossterm", branch = "bug_fix" }
```
I did a fix wich should solve the problem.

**Comment by VladimirMarkelov** [comment]
Yes, thank you!

The test application runs and prints terminal size without any any issue.

Issue can be closed.

**Comment by TimonPost** [comment]
I'll be releasing 0.5.4 soon!

**Comment by TimonPost** [comment]
Release has been done you can upgrade to 0.5.4

**Comment by VladimirMarkelov** [comment]
Thanks! The new release works great on Window 7
