### ISSUE TITLE
Is possible to handle key input event?

### ISSUE THREAD

**Issue by sbwtw** [TimonPost/crossterm#75]
I saw the `TerminalInput` can be used to read a char or a hole line of input. But I want to read a key event, like Up(↑) or Down(↓). Is any way to do this?

**Comment by TimonPost** [comment]
Not yet, it is on the todo list for crossterm and I am not sure when I have time to implement this right now. (for now, you can use w a s d for moving, just saying, at least if you want that :))

**Comment by TimonPost** [comment]
#111 will implement this.
