### ISSUE TITLE
Set multiple markers (like with Vim)?

### ISSUE THREAD

**Issue by imdaveho** [TimonPost/crossterm#76]
The comments for `cursor.save_position` and `cursor.reset_position` aren't clear as to whether the position is single use?

Is it possible to use this API to make something like markers in Vim where you can set up to N markers to jump around in the screeen?

**Comment by imdaveho** [comment]
ahh nevermind --> I can easily store the x, y coordinates and restore them with custom code using `goto`

**Comment by TimonPost** [comment]
Ah oke, I'll see if I can improve the doc. And yes, you can do this in your own custom code. crossterm is meant for providing some more basic functionality and having markers and such is going above crossterms purpose.
