### ISSUE TITLE
Multiple inputs = multiple threads for AsyncReader?

### ISSUE THREAD

**Issue by imdaveho** [TimonPost/crossterm#79]
I am trying to implement a toy terminal app that can open up multiple files in alternate screens for editing.

It is not clear from the comments/documentation, that using the recommended 

```rust
let input = crossterm::input::from_screen(&screen);
let stdin = input.read_async().bytes();
```

creates a new thread per call to `input.read_async()`.

Do the threads end after the screen gets dropped?

**Comment by TimonPost** [comment]
Actually, the thread for `read_async` is never aborted when it is created. And yes a thread is created per call. Should this be fixed? yes it should.  

This is actualy a good issue to leave open and needs further investication.

###Task

`input.read_async()` creates a thread to read input. Make this thread also disposable when the `AsyncReader` is dropped

## Issue
Threads are not disposed of when calling `input.read_async()`

**Comment by TimonPost** [comment]
This is fixed on `input_handling` branch. Will be merged soon.

**Comment by TimonPost** [comment]
#111 will implement this.
