### ISSUE TITLE
Input events not consistent between *nix and Windows

### ISSUE THREAD

**Issue by imdaveho** [TimonPost/crossterm#80]
Pressing up, down, left, right arrows, delete, insert, home, F1-10, and Alt + Shift + <letter> in read_async_demo() all returns some kind of byte sequence as captured by tty.

On Windows, however, these inputs crash the program or cause it to lock up. Is there a way to handle these inputs as well? Or be explicit in the docs regarding the limitations.

I could try to help, if it's regarding documentation, but I have limited exposure to how terminals work between posix and windows. If you could point me in the right direction, perhaps I can help later down the line.

EDIT: 
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/078sfkak(v=vs.110)

For some keys or key sequences, like arrows, all that is needed is to call the _getwch or _getwche a second time. I think all that is needed is to remove this: https://github.com/TimonPost/crossterm/blob/master/src/modules/input/windows_input.rs#L72 

or have a different kind of error detection than 0 or 0xe0...like calling _getwch() a second time with kbhit() --> https://github.com/genotrance/snip/blob/master/src/snip/key.nim#L35

**Comment by TimonPost** [comment]
Thanks for looking into this. Yes this is on the feature list and is not yet supported. I'm not familiar with those keys so have to do some research first. I'll have another comment fort.

**Comment by TimonPost** [comment]
closing in favor of #81
