### ISSUE TITLE
Tui backend: Getting crossterm::common::screen::screen::Screen Screen from backend instead of crossterm::Screen

### ISSUE THREAD

**Issue by JonBoyleCoding** [TimonPost/crossterm#86]
This is probably an issue with tui-rs (feel free to close if it is), but in case it can be solved here I thought I'd mention it. tui-rs issue is posted here: https://github.com/fdehau/tui-rs/issues/123

```
error[E0308]: mismatched types
  --> src/main.rs:70:46
   |
70 |     let scr = crossterm::Crossterm::from_screen(term.backend().screen());
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `crossterm::Screen`, found struct `crossterm::common::screen::screen::Screen`
   |
   = note: expected type `&crossterm::Screen`
              found type `&crossterm::common::screen::screen::Screen`
```

I'm doing this with an attempt to access it's input handler, as it seems like just running it async doesn't seem to work (keep getting "No Characters Pressed" String error when calling next on AsyncReader).

**Comment by TimonPost** [comment]
That is weird, the error: "No Characters Pressed" is the error you get when you don't press any keys. When calling next and a character is pressed this is supposed to return the character.

**Comment by JonBoyleCoding** [comment]
If you don't mind, I'll prepare a code example to check if I'm doing it correctly?

**Comment by TimonPost** [comment]
Yes, sure.

**Comment by JonBoyleCoding** [comment]
Hmm... weird. My example I made is working fine now. Perhaps it had something to do with me using an ssh connection at the time. I shall close the issue.
