### ISSUE TITLE
termion style ansi api

### ISSUE THREAD

**Issue by prabirshrestha** [TimonPost/crossterm#87]
I do like how it is very easy to get started with termion because it just uses ansi escape sequences. Would it be possible to support something similar in crossterm?

```rust
let stdout = MouseTerminal::from(AlternateScreen::from(io::stdout().into_raw_mode().unwrap()));
write!(stdout,
    "{}{}{}{}Hi{}",
    cursor::Hide, 
    clear::All,
    cursor::Goto(0,0),
    color::Fg(color::Red),
    cursor::Show);
stdout.flush();
```

For terminals that do not support it might need to add custom parser though it could be a bit slow.

**Comment by TimonPost** [comment]
I do have those on my [todo list](https://github.com/TimonPost/crossterm/tree/master/crossterm_style#features), however, it is a bit difficult to realize.

**Comment by TimonPost** [comment]
I have implemented it and will be soon usable. 

_preview_
```
println!("{} Underlined {} No Underline", Attribute::Underlined, Attribute::NoUnderline);
println!("{}{} Red on Yellow", Colored::Fg(Color::Red), Colored::Bg(Color::Yellow));
println!("{}", "aa".green())
```

**Comment by TimonPost** [comment]
Closing this will be soon available in crossterm_style `0.2`

**Comment by prabirshrestha** [comment]
Looking forward to it. Checked the source out and seems like I only see it for colors. Are there plans to support cursors and clear screen?

**Comment by prabirshrestha** [comment]
Great. Looking forward for those so I can migrate to `crossterm` instead of `termion`.

**Comment by prabirshrestha** [comment]
Any plans on bringing cursor and clear api? Let me know if I should file a new issue to track it.

**Comment by TimonPost** [comment]
I am not sure if that is something I want, I was thinking about it. But does it really make sense to make the cursor move with a write operation like: `write!(stdout, "{}", Cursor::Goto(10,20))`

**Comment by prabirshrestha** [comment]
My thought was that there would be applications that just uses those sequence so instead of me parsing and converting crossterm, it would automatically do it for me.

One thing I miss a lot on windows is tmux. Imagine if I could spawn a pty process and just directly pipe it to crossterm. It also allows one to easily create other emebedded terminal support such as in vim with crossterm very easily. Creating apps like these would be very easy if crossterm natively supported it. https://github.com/wez/wezterm. 

Other interesting cases I can see is having OpenGL or directx for backends. So if I wanted to created a gvim I can easily use the gui backends instead of terminal. As a dev consuming crossterm I would be very happy because all the hard work is handled by crossterm.

**Comment by TimonPost** [comment]
Crossterm supports a similar feature with the command API since version 0.10
