### ISSUE TITLE
Windows 10: Getting mode failed

### ISSUE THREAD

**Issue by Rukenshia** [TimonPost/crossterm#90]
This seems to be similar to last years issue of #15 . I just had a user report this issue on Windows 10.

He is using Powershell without Administrator rights on his machine. He can't try it on cmd, only Powershell.

This code triggers the issue:

```
    println!("\nWelcome to saml2aws-auto. Let's configure a few things to get started.");
    println!("Currently, only Keycloak is supported as Identity Provider. When setting the");
    println!(
        "IDP URL, please note that you will have to pass {} of Keycloak.\n",
        style("the exact path to the saml client")
            .with(Color::Yellow)
            
    );
```

it seems to be this line that fails: https://github.com/TimonPost/crossterm/blob/ad74f6b5242e6ed998bef6240b738785ea449ffe/crossterm_winapi/src/console_mode.rs#L53

The crossterm version is the latest.
If there are any additional steps I can do to get you more information please let me know, I want to help as much as I can here.

Thanks!

**Comment by TimonPost** [comment]
Okay, let me type Some test code. You have access to the machine? 

GetConsoleMode is a winapi method which should just work.

**Comment by Rukenshia** [comment]
I don't have access to the machine but I can send him an updated binary with any test code to run it on his machine.

Thanks for getting back this quickly, you're awesome!

**Comment by TimonPost** [comment]
Wich version does it run?

**Comment by Rukenshia** [comment]
@TimonPost he got back to me and said he got it working on his private machine, but not on his work computer which has a restriction on it (not being allowed to use cmd), but PowerShell works. So I'm not entirely sure and will get back to him. My program [saml2aws-auto](https://github.com/Rukenshia/saml2aws-auto) uses crossterm 0.6.0.

**Comment by TimonPost** [comment]
I don't know what the problem here is. Maybe rights to get console mode is not permitted by his working PC. But that is outside the scope of this crate, I think I can't help you further here.
