### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by ignatenkobrain** [TimonPost/crossterm#99]
License text needs to be added both in top directory and in each crate (you can use symlink for that).

Thanks in advance!

**Comment by TimonPost** [comment]
Yea, good point, on it!

**Comment by TimonPost** [comment]
done

**Comment by ignatenkobrain** [comment]
@TimonPost Unfortunately you didn't add it into sub-crates. Can you do it, please?

**Comment by TimonPost** [comment]
https://github.com/TimonPost/crossterm#license it applies to all crates.

**Comment by ignatenkobrain** [comment]
Unfortunately it is not enough because archives on crates.io do not ship license file. The easiest fix is to go to each folder and create symlink to main LICENSE file. That will make all crates to have LICENSE file on crates.io tarball.
